/*
 * ultrasonic.c
 *
 *  Created on: Jun 17, 2023
 *      Author: user
 */
/*-------------------------------INCLUDES---------------------------------*/
#include "ultrasonic.h"
#include "gpio.h"
#include "icu.h"
#include "lcd.h"
#include <util/delay.h>
#include "math.h"

/*******************************************************************************
 *                      Global Variables                                  *
 *******************************************************************************/
static uint8 g_edgeCount = 0;
static uint16 g_time =0;
static uint16 distance = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************/
/*
 * Description : Initialize the ICU driver as required.
 *  			 Setup the ICU call back function.
 *  			 Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void)
{
	GPIO_setupPinDirection(PORTB_ID, PIN5_ID, PIN_OUTPUT);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
	ICU_ConfigType config= {F_CPU_8,RAISING};
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	ICU_init(&config);
}

/*
 * Description : Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void)
{
	/*
	 * transmit 10 us trigger pulse to the Ultrasonic
	 */
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID, PIN5_ID, LOGIC_LOW);

}

/*
 * Description : Send the trigger pulse by using Ultrasonic_Trigger function
 *  			 Start the measurements by the ICU from this moment
 */
uint16 Ultrasonic_readDistance(void)
{

	Ultrasonic_Trigger();

	distance = g_time*0.01715; /* equation to get the distance*/
	if(distance >= MIN_DISTANCE && distance <= MAX_DISTANCE)
	{
		if(distance>=342){
			return distance+3;
		}
		else if(distance>=154)
		{
			return distance+2;
		}
		else
		{
			return distance+1;
		}
	}

	return 1;

	/*
	 * other solution:if speed of sound = 340
	 * static float distance = calculate_distance_340();
	 *
	 */
}

/*
 * Description : This is the call back function called by the ICU driver.
 *  			 This is used to calculate the high time (pulse time) generated by the ultrasonic sensor.
 */
void Ultrasonic_edgeProcessing(void)
{
	g_edgeCount++;
	if(g_edgeCount==1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount ==2)
	{
		g_time = ICU_getInputCaptureValue();
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(RAISING);
		g_edgeCount=0;
	}
}


uint8 calculate_distance_340()
{
	distance = g_time/58.8 ;
	if(distance>=59 && distance < 130.5)
	{
		distance+=2;
	}
	else if (distance >130.5 && distance <130.8)
	{
		distance+=3;
	}
	else if(distance >130.8 && distance <131.5)
	{
		distance+=2;
	}
	else if(distance>131.5 && distance <203.5)
	{
		distance+=3;
	}
	else if(distance >203.5 && distance <276.5)
	{
		distance+=4;
	}
	else if( distance >276.5 && distance <348.5)
	{
		distance+=5;
	}
	else if(distance >348.5)
	{
		distance+=6;
	}

	else if(distance>58.5 && distance <59)
	{
		distance+=2;
	}

	else
	{
		distance+=1;
	}


	return distance;
}
